version: 2

before:
  hooks:
    - cp config.toml.example ./config.toml
builds:
-
  id: crawler
  binary: crawler
  main: ./main.go
  ldflags:
    - -s -w -X github.com/italia/publiccode-crawler/v4/internal.VERSION={{.Version}} -X github.com/italia/publiccode-crawler/v4/internal.BuildTime={{.Date}}
  env:
  - CGO_ENABLED=0
  hooks:
    post: cp config.toml {{ dir .Path }}/config.toml
archives:
-
  builds:
    - crawler
  wrap_in_directory: false
  files:
    - config.toml
  name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end }}
  format_overrides:
    - goos: windows
      formats: [zip]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
