---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "publiccode-crawler.fullname" . }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.cronjob_schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: "{{ template "publiccode-crawler.fullname" . }}"
        spec:
          securityContext:
            fsGroup: 1000

          containers:
          - name: {{ template "publiccode-crawler.fullname" . }}
            image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}

            command:
              - publiccode-crawler
            args:
              - crawl

            resources:
              {{- toYaml .Values.resources | indent 14 }}
            env:
              - name: API_BASEURL
                value: "{{ .Values.env.API_BASEURL}}"
              - name: MAIN_PUBLISHER_ID
                value: "{{ .Values.env.MAIN_PUBLISHER_ID }}"
              - name: SKIP_VITALITY
                value: "{{ .Values.env.SKIP_VITALITY }}"
              - name: API_BEARER_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ default (include "publiccode-crawler.fullname" .) .Values.useExistingSecret }}
                    key: api-bearer-token
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ default (include "publiccode-crawler.fullname" .) .Values.useExistingSecret }}
                    key: github-token

          restartPolicy: Never
