{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "publiccode-crawler.fullname" . }}
  labels:
    {{- include "publiccode-crawler.labels" . | nindent 4 }}
type: Opaque
data:
  api-bearer-token: {{ .Values.secrets.apiBearerToken | b64enc }}
  github-token: {{ .Values.secrets.githubToken | b64enc }}
{{- end }}
