on:
  push:
    tags:
      - helm/*

permissions: {}

jobs:
  release_chart:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF_NAME#helm/}" >> $GITHUB_ENV
      - name: Push chart to GitHub Container Registry
        uses: appany/helm-oci-chart-releaser@d94988c92bed2e09c6113981f15f8bb495d10943 # v0.5.0
        with:
          name: publiccode-crawler
          repository: ${{ github.repository }}/charts
          tag: ${{ env.version }}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
