on:
  push:
    tags:
      - helm/*

permissions:
  packages: write

jobs:
  release_chart:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF_NAME#helm/}" >> $GITHUB_ENV
      - name: Push chart to GitHub Container Registry
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: publiccode-crawler
          repository: ${{ github.repository }}/charts
          tag: ${{ env.version }}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
